-d E:\hafta5\fpga_beyaz_led\impl\gwsynthesis\fpga_beyaz_led.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst E:\hafta5\fpga_beyaz_led\src\fpga_beyaz_led.cst
-cfg E:\hafta5\fpga_beyaz_led\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
